### PR TITLE
chore: update deps

### LINKED ISSUE #7: bump packages version, use `Deno.serve`
### Describe the bug

image

- the page is using outdated std (0.147.0, compared to latest 0.210.0)
- [serve](https://deno.land/std@0.210.0/http/server.ts?s=serve) is deprecated and will be removed in deno 1.0.0 

### Reproduction

https://github.com/ydcjeff/shield.deno.dev/blob/4f69dd51317103e800b517a896f24be128c99ed6/mod.ts#L1-L2

### PR DESCRIPTION
**Pull request by scarf005**
### Description

- resolves #7 

### Additional context

this PR also adds [lockfiles](https://docs.deno.com/runtime/manual/basics/modules/integrity_checking) for better reproducibility.

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### CODE REVIEW

**Review by jeffydc — CHANGES_REQUESTED** [review]
Thank you for the PR. Can you add `lock: false` to deno config and remove the lockfile since we are using exact versions of the modules?

**Comment by scarf005** [comment]
alright. may i ask the rationale for not using lockfiles?

**Comment by jeffydc** [comment]
We are using the exact versions of the modules, so we don't need lock file.

**Comment by scarf005** [comment]
there's two major dangers even if we provide exact version of the modules.

```
// foo.ts
import { bar } from "https://deno.land/x/bar@1.0.0/mod.ts"
```

1. we cannot ensure that the URL will return the same response. highly unlikely, but let's assume deno.land is hacked. "https://deno.land/x/bar@1.0.0/mod.ts" might return modified version of `bar` which contains malacious code (e.g Dos attack).
2. even if the dependency is secure, we cannot ensure the _dependency's dependencies_ are safe. for example,
```
// bar.ts
import { baz } from "https://deno.land/x/baz/mod.ts"
import { qux } from "https://foo.bar.com/x/qux@1.0.0/mod.ts"
```
- as `baz` is not exactly versioned (and we cannot control it), a new breaking change from `baz` will also break `bar`.
- `foo.bar.com` might return different response, which we also cannot control.

## Conclusion

since there's no downsides to adding lockfiles but only upsides, i suggest keeping the lockfiles in (even it's std)

## Further Read

> But what happens if the content in the remote url https://some.url/a.ts is changed? This could lead to your production module running with different dependency code than your local module. Deno's solution to avoid this is to use integrity checking and lock files.

- https://docs.deno.com/runtime/manual/basics/modules/integrity_checking#introduction
- https://snyk.io/blog/npm-security-preventing-supply-chain-attacks/

**Review by jeffydc — APPROVED** [review]
Thanks for the detailed response.

**Pull request merged**
